Parameters:
  LatestAmiId:
    Type: 'AWS::SSM::Parameter::Value<AWS::EC2::Image::Id>'
    Default: '/aws/service/ami-amazon-linux-latest/amzn2-ami-hvm-arm64-gp2'
  InstanceType:
    Type: String
    Default: t4g.small
    AllowedValues:
      - "t4g.small"
      - "t4g.medium"
      - "t4g.large"
  AdditionalVolumeSize:
    Type: Number
    Default: 20

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: !Ref LatestAmiId
      InstanceType: !Ref InstanceType
      KeyName: dmichael
      SubnetId: subnet-edb0f4a1
      SecurityGroupIds:
        - !GetAtt SSHSecurityGroup.GroupId
        - !GetAtt HTTPSecurityGroup.GroupId
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 20
      UserData:
        Fn::Base64: |
          #!/bin/bash
          # Install and start web server process
          yum install -y httpd
          systemctl start httpd
          echo "Hello World!" > /var/www/html/index.html
  NewVolume:
    Type: AWS::EC2::Volume
    Properties:
      Size: !Ref AdditionalVolumeSize
      Encrypted: true
      VolumeType: gp3
      AvailabilityZone: !GetAtt MyInstance.AvailabilityZone
  VolumeAttachment:
    Type: AWS::EC2::VolumeAttachment
    Properties:
      Device: /dev/sdh
      InstanceId: !Ref MyInstance
      VolumeId: !Ref NewVolume
  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH Access
      VpcId: vpc-6a15aa01
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 172.16.0.0/12
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 192.168.0.0/16
  HTTPSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH Access
      VpcId: vpc-6a15aa01
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 10.0.0.0/8
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 172.16.0.0/12
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 192.168.0.0/16
